# updates exiting pkgdown site for a repository
# deploys to a branch gh-pages
name: call-update-pkgdown
# on specifies the build triggers. See more info at https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
# [build-trigger-goes-here]

# Give the fewest permissions possible. content is necessary.
# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
permissions:
  contents: write

jobs:
  call-workflow:
    uses: nmfs-ost/ghactions4r/.github/workflows/update-pkgdown.yml@main
