# document and style  using reusable workflow
on:
  workflow_dispatch:
  push:
name: call-doc-and-style-r
jobs:
  call-workflow:
    uses: nmfs-ost/ghactions4r/.github/workflows/doc-and-style-r.yml@add-air
    with:
      use-air: true
