# Run r cmd check
on:
  workflow_dispatch:
  push:
   paths-ignore:
     - '.github/workflows/call**'
  pull_request:
    paths-ignore:
      - '.github/workflows/call**'
  schedule:
    # This should run the default branch weekly on sunday
    - cron: '0 0 * * 0'
name: call-r-cmd-check

# no permissions are needed by the default github token for this workflow to 
# run, so don't pass any.
# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
permissions: {}

jobs:
  call-workflow:
    uses: nmfs-ost/ghactions4r/.github/workflows/r-cmd-check.yml@main