# document and style  using reusable workflow
on:
  pull_request:
name: call-doc-and-style-r
jobs:
  call-workflow:
    uses: nmfs-ost/ghactions4r/.github/workflows/doc-and-style-r.yml@test-again-issue-154
