# document and style  using reusable workflow
name: call-doc-and-style-r

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: 
      - 'R/**'
      - 'tests/**'
      - 'vignettes/**'

# Give the fewest permissions possible. content and pull-requests are necessary.
# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
permissions:
  contents: write
  pull-requests: write

jobs:
  call-workflow:
    uses: nmfs-ost/ghactions4r/.github/workflows/doc-and-style-r.yml@main
