name: doc-and-style-r-cmds

on:
  workflow_call:
    inputs:
      run-rm_dollar_sign:
        required: false
        type: boolean
        default: false
      commit-directly:
        required: false
        type: boolean
        default: false
      use-air:
        required: false
        type: boolean
        default: false

permissions:
  contents: write
  pull-requests: write

jobs:
  doc-and-style-r-cmds:
    name: Doc and Style commands
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Checkout the PR branch
        uses: actions/checkout@v5
      
      - name: Get original PR branch name
        id: get_branch
        run: |
          PR_URL="${{ github.event.issue.pull_request.url }}"
          PR_NUM=$(basename "$PR_URL")
          BRANCH_NAME=$(gh pr view $PR_NUM --json headRefName -q .headRefName)
          echo "The original PR branch is: $BRANCH_NAME"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout the PR branch
        uses: actions/checkout@v5
        with:
          ref: ${{ steps.get_branch.outputs.branch_name }}
      - name: Install curl dependency
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev

      - name: Install Air
        if: inputs.use-air == true
        uses: posit-dev/setup-air@v1

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        if: inputs.use-air == false
        with:
          extra-packages: |
            remotes
            styler
            roxygen2
            usethis

      - uses: r-lib/actions/setup-r-dependencies@v2
        if: inputs.use-air == true
        with:
          extra-packages: |
            remotes
            roxygen2
            usethis

      - name: add ghactions4r, if using ghactions4r::rm_dollar_sign
        if: inputs.run-rm_dollar_sign == true 
        run: Rscript -e 'remotes::install_github("nmfs-ost/ghactions4r", upgrade = "always")'

      
      - name: Style using Air
        if: inputs.use-air == true
        run: air format .

      - name: Style using styler
        if: inputs.use-air == false
        run: |
          results <- styler::style_pkg()
          if (any(is.na(results[["changed"]]))) {
            stop("styler threw an error")
          }
        shell: Rscript {0}

      - name: Document
        run: Rscript -e 'roxygen2::roxygenise()'

      - name: Run run-rm_dollar_sign
        if: inputs.run-rm_dollar_sign == true
        run: |
          files_to_change <- list.files("R", full.names = TRUE)
          to_rm <- grep("rm_dollar_sign", files_to_change)
          if(isTRUE(length(to_rm)>0)) {
            files_to_change <- files_to_change[-to_rm]
          }
          out <- lapply(files_to_change, function(x) ghactions4r::rm_dollar_sign(x))
        shell: Rscript {0}

      - name: Style again using Styler
        if: inputs.use-air == false
        run: | 
          results <- styler::style_pkg()
          if (any(is.na(results[["changed"]]))) {
            stop("styler threw an error")
          }
        shell: Rscript {0}
      
      - name: Style again using Air
        if: inputs.use-air == true
        run: air format .

      - name: Document again, just in case
        run: |
          Rscript -e 'roxygen2::roxygenise()'
        
      - name: Style description file
        run: Rscript -e 'usethis::use_tidy_description()'
      
      - name: Remove any rds in .github
        run: cd .github && rm -f *.rds
      - name: Remove any .Rds in .github
        run: cd .github && rm -f *.Rds
      - name: Remove any R-version file in .github
        run: cd .github && rm -f R-version
        
      - name: commit if using commit directly
        if: inputs.commit-directly == true
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: 'style and docs: run devtools::document() and styler::style_pkg()'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: 'style and docs: run devtools::document() and styler::style_pkg()'
          branch: "style-${{ github.run_id }}"
          base: ${{ steps.get_branch.outputs.branch_name }}
          title: 'Style code and document'
          body: |
           Auto-generated by [doc-and-style-r-cmds.yml][1]


             [1]: https://github.com/nmfs-ost/ghactions4r/tree/main/.github/workflows/doc-and-style-r-cmds.yml