name: doc-and-style-r-cmds

on:
  workflow_call:

permissions:
  contents: write
  pull-requests: write

jobs:
  doc-and-style-r-cmds:
    name: style
    runs-on: ubuntu-latest
    steps:

# added if statement to show how to run this if it only is on issue comment. This could be useful to incorporate into style and doc.
      - name: Checkout the PR branch
        uses: actions/checkout@v4
      
      - name: Get original PR branch name
        id: get_branch
        # if: github.event_name == 'issue_comment'
        run: |
          PR_URL="${{ github.event.issue.pull_request.url }}"
          PR_NUM=$(basename "$PR_URL")
          BRANCH_NAME=$(gh pr view $PR_NUM --json headRefName -q .headRefName)
          echo "The original PR branch is: $BRANCH_NAME"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout the PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.get_branch.outputs.branch_name }}
  
      - name: setup air 
        uses: posit-dev/setup-air@v1

      - name: run air to make changes
        run: air format .
      
      # - name: specify base branch
      #   id: specify-base
      #   if: ${{ inputs.commit-directly == false }}
      #   run: |
      #     if [ -n ${{ github.head_ref }} ]; then
      #       echo "base=${{github.head_ref}}" >> "$GITHUB_OUTPUT"
      #     elif [ -n ${{ github.ref_name }} ]; then
      #       echo "base=${{github.ref_name}}" >> "$GITHUB_OUTPUT"
      #     else
      #       echo "both github.head_ref and github.ref_name do not exist" >&2
      #       exit 1
      #     fi  
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: 'style and docs: run devtools::document() and styler::style_pkg()'
          branch: "style-${{ github.run_id }}"
          base: ${{ steps.get_branch.outputs.branch_name }}
          title: 'Style code and document'
          body: |
           Auto-generated by [doc-and-style-r.yml][1]


             [1]: https://github.com/nmfs-ost/ghactions4r/tree/main/.github/workflows/doc-and-style-r.yml