# render Quarto
on:
  workflow_call:
    inputs:
      folder-path:
        required: false
        type: string
        default: '.'
      use-renv:
        required: false
        type: boolean
        default: false

name: render quarto and save as artifact
jobs:
  render-quarto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        # note: may want to replace render quarto with just calling quarto render on the command line.
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # user should have their dependencies in a DESCRIPTION file in their project
      - name: Install dependencies in DESCRIPTION file
        if: inputs.use-renv == false
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Install dependencies with renv
        if: inputs.use-renv == true
        uses: r-lib/actions/setup-renv@v2
        
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: ${{ inputs.folder-path }}

      - name: save artifact
        uses: actions/upload-artifact@v4
        with:
          name: quarto-output
          path: ${{ inputs.folder-path }}/_site
